name: Static Code Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run SonarQube Analysis
      - name: SonarQube Analysis
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: maya-abdoh_HiveBox  
          args: >
            -Dsonar.projectKey=maya-abdoh_HiveBox
            -Dsonar.language=python
            -Dsonar.host.url=https://sonarcloud.io/

      # Step 5: Run Semgrep Analysis for Python
      - name: Run Semgrep Analysis for Python
        uses: returntocorp/semgrep-action@v1
        with:
          config: "python"
