name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code and Dockerfile
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Lint Dockerfile using Hadolint
      - name: Lint Dockerfile
        run: hadolint Dockerfile

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Lint Python code
      - name: Lint Python code
        run: pylint your_fastapi_app/

  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      docker:
        image: fastapi-app
        options: --entrypoint "/bin/bash"
        ports:
          - 8000:8000

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install test dependencies
      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt

      # Run unit tests
      - name: Run tests
        run: pytest

  openssf-scorecard:
    name: OpenSSF Scorecard Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run OpenSSF Scorecard
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.1.1

      # Fix Scorecard issues
      - name: Fix security issues
        run: |
          # Add any commands needed to fix issues based on Scorecard output
          echo "Fixing Scorecard issues"
